---
# tasks file for ansible-telegraf
- name: "Install telegraf on server"
  include: installTelegraf.yml

- name: "Copy telegraf output plugin"
  template:
    src: "200-output.conf.js2"
    dest: "/etc/telegraf/telegraf.d/200-output.conf"
  become: yes
  notify: "Restart Telegraf"